sbatch launch_sbatch_sourcing_endeavor.sh 0 .01
sbatch launch_sbatch_sourcing_endeavor.sh .01 .02
sbatch launch_sbatch_sourcing_endeavor.sh .02 .03
sbatch launch_sbatch_sourcing_endeavor.sh .03 .04
sbatch launch_sbatch_sourcing_endeavor.sh .04 .05
sbatch launch_sbatch_sourcing_endeavor.sh .05 .06
sbatch launch_sbatch_sourcing_endeavor.sh .06 .07
sbatch launch_sbatch_sourcing_endeavor.sh .07 .08
sbatch launch_sbatch_sourcing_endeavor.sh .08 .09
sbatch launch_sbatch_sourcing_endeavor.sh .09 .1
sbatch launch_sbatch_sourcing_endeavor.sh .1 .11
sbatch launch_sbatch_sourcing_endeavor.sh .11 .12
sbatch launch_sbatch_sourcing_endeavor.sh .12 .13
sbatch launch_sbatch_sourcing_endeavor.sh .13 .14
sbatch launch_sbatch_sourcing_endeavor.sh .14 .15
sbatch launch_sbatch_sourcing_endeavor.sh .15 .16
sbatch launch_sbatch_sourcing_endeavor.sh .16 .17
sbatch launch_sbatch_sourcing_endeavor.sh .17 .18
sbatch launch_sbatch_sourcing_endeavor.sh .18 .19
sbatch launch_sbatch_sourcing_endeavor.sh .19 .2
sbatch launch_sbatch_sourcing_endeavor.sh .2 .21
sbatch launch_sbatch_sourcing_endeavor.sh .21 .22
sbatch launch_sbatch_sourcing_endeavor.sh .22 .23
sbatch launch_sbatch_sourcing_endeavor.sh .23 .24
sbatch launch_sbatch_sourcing_endeavor.sh .24 .25
sbatch launch_sbatch_sourcing_endeavor.sh .25 .26
sbatch launch_sbatch_sourcing_endeavor.sh .26 .27
sbatch launch_sbatch_sourcing_endeavor.sh .27 .28
sbatch launch_sbatch_sourcing_endeavor.sh .28 .29
sbatch launch_sbatch_sourcing_endeavor.sh .29 .3
sbatch launch_sbatch_sourcing_endeavor.sh .3 .31
sbatch launch_sbatch_sourcing_endeavor.sh .31 .32
sbatch launch_sbatch_sourcing_endeavor.sh .32 .33
sbatch launch_sbatch_sourcing_endeavor.sh .33 .34
sbatch launch_sbatch_sourcing_endeavor.sh .34 .35
sbatch launch_sbatch_sourcing_endeavor.sh .35 .36
sbatch launch_sbatch_sourcing_endeavor.sh .36 .37
sbatch launch_sbatch_sourcing_endeavor.sh .37 .38
sbatch launch_sbatch_sourcing_endeavor.sh .38 .39
sbatch launch_sbatch_sourcing_endeavor.sh .39 .4
sbatch launch_sbatch_sourcing_endeavor.sh .4 .41
sbatch launch_sbatch_sourcing_endeavor.sh .41 .42
sbatch launch_sbatch_sourcing_endeavor.sh .42 .43
sbatch launch_sbatch_sourcing_endeavor.sh .43 .44
sbatch launch_sbatch_sourcing_endeavor.sh .44 .45
sbatch launch_sbatch_sourcing_endeavor.sh .45 .46
sbatch launch_sbatch_sourcing_endeavor.sh .46 .47
sbatch launch_sbatch_sourcing_endeavor.sh .47 .48
sbatch launch_sbatch_sourcing_endeavor.sh .48 .49
sbatch launch_sbatch_sourcing_endeavor.sh .49 .5
sbatch launch_sbatch_sourcing_endeavor.sh .5 .51
sbatch launch_sbatch_sourcing_endeavor.sh .51 .52
sbatch launch_sbatch_sourcing_endeavor.sh .52 .53
sbatch launch_sbatch_sourcing_endeavor.sh .53 .54
sbatch launch_sbatch_sourcing_endeavor.sh .54 .55
sbatch launch_sbatch_sourcing_endeavor.sh .55 .56
sbatch launch_sbatch_sourcing_endeavor.sh .56 .57
sbatch launch_sbatch_sourcing_endeavor.sh .57 .58
sbatch launch_sbatch_sourcing_endeavor.sh .58 .59
sbatch launch_sbatch_sourcing_endeavor.sh .59 .6
sbatch launch_sbatch_sourcing_endeavor.sh .6 .61
sbatch launch_sbatch_sourcing_endeavor.sh .61 .62
sbatch launch_sbatch_sourcing_endeavor.sh .62 .63
sbatch launch_sbatch_sourcing_endeavor.sh .63 .64
sbatch launch_sbatch_sourcing_endeavor.sh .64 .65
sbatch launch_sbatch_sourcing_endeavor.sh .65 .66
sbatch launch_sbatch_sourcing_endeavor.sh .66 .67
sbatch launch_sbatch_sourcing_endeavor.sh .67 .68
sbatch launch_sbatch_sourcing_endeavor.sh .68 .69
sbatch launch_sbatch_sourcing_endeavor.sh .69 .7
sbatch launch_sbatch_sourcing_endeavor.sh .7 .71
sbatch launch_sbatch_sourcing_endeavor.sh .71 .72
sbatch launch_sbatch_sourcing_endeavor.sh .72 .73
sbatch launch_sbatch_sourcing_endeavor.sh .73 .74
sbatch launch_sbatch_sourcing_endeavor.sh .74 .75
sbatch launch_sbatch_sourcing_endeavor.sh .75 .76
sbatch launch_sbatch_sourcing_endeavor.sh .76 .77
sbatch launch_sbatch_sourcing_endeavor.sh .77 .78
sbatch launch_sbatch_sourcing_endeavor.sh .78 .79
sbatch launch_sbatch_sourcing_endeavor.sh .79 .8
sbatch launch_sbatch_sourcing_endeavor.sh .8 .81
sbatch launch_sbatch_sourcing_endeavor.sh .81 .82
sbatch launch_sbatch_sourcing_endeavor.sh .82 .83
sbatch launch_sbatch_sourcing_endeavor.sh .83 .84
sbatch launch_sbatch_sourcing_endeavor.sh .84 .85
sbatch launch_sbatch_sourcing_endeavor.sh .85 .86
sbatch launch_sbatch_sourcing_endeavor.sh .86 .87
sbatch launch_sbatch_sourcing_endeavor.sh .87 .88
sbatch launch_sbatch_sourcing_endeavor.sh .88 .89
sbatch launch_sbatch_sourcing_endeavor.sh .89 .9
sbatch launch_sbatch_sourcing_endeavor.sh .9 .91
sbatch launch_sbatch_sourcing_endeavor.sh .91 .92
sbatch launch_sbatch_sourcing_endeavor.sh .92 .93
sbatch launch_sbatch_sourcing_endeavor.sh .93 .94
sbatch launch_sbatch_sourcing_endeavor.sh .94 .95
sbatch launch_sbatch_sourcing_endeavor.sh .95 .96
sbatch launch_sbatch_sourcing_endeavor.sh .96 .97
sbatch launch_sbatch_sourcing_endeavor.sh .97 .98
sbatch launch_sbatch_sourcing_endeavor.sh .98 .99
sbatch launch_sbatch_sourcing_endeavor.sh .99 1
