sbatch launch_sbatch_coref_endeavour.sh 0 5
sbatch launch_sbatch_coref_endeavour.sh 5 10
sbatch launch_sbatch_coref_endeavour.sh 10 15
sbatch launch_sbatch_coref_endeavour.sh 15 20
sbatch launch_sbatch_coref_endeavour.sh 20 25
sbatch launch_sbatch_coref_endeavour.sh 25 30
sbatch launch_sbatch_coref_endeavour.sh 30 35
sbatch launch_sbatch_coref_endeavour.sh 35 40
sbatch launch_sbatch_coref_endeavour.sh 40 45
sbatch launch_sbatch_coref_endeavour.sh 45 50
sbatch launch_sbatch_coref_endeavour.sh 50 55
sbatch launch_sbatch_coref_endeavour.sh 55 60
sbatch launch_sbatch_coref_endeavour.sh 60 65
sbatch launch_sbatch_coref_endeavour.sh 65 70
sbatch launch_sbatch_coref_endeavour.sh 70 75
sbatch launch_sbatch_coref_endeavour.sh 75 80
sbatch launch_sbatch_coref_endeavour.sh 80 85
sbatch launch_sbatch_coref_endeavour.sh 85 90
sbatch launch_sbatch_coref_endeavour.sh 90 95
sbatch launch_sbatch_coref_endeavour.sh 95 100

