sbatch launch_sbatch_stance_mit.sh 0 .05
sbatch launch_sbatch_stance_mit.sh .05 .1
sbatch launch_sbatch_stance_mit.sh .1 .15
sbatch launch_sbatch_stance_mit.sh .15 .2
sbatch launch_sbatch_stance_mit.sh .2 .25
sbatch launch_sbatch_stance_mit.sh .25 .3
sbatch launch_sbatch_stance_mit.sh .3 .35
sbatch launch_sbatch_stance_mit.sh .35 .4
sbatch launch_sbatch_stance_mit.sh .4 .45
sbatch launch_sbatch_stance_mit.sh .45 .5
sbatch launch_sbatch_stance_mit.sh .5 .55
sbatch launch_sbatch_stance_mit.sh .55 .6
sbatch launch_sbatch_stance_mit.sh .6 .65
sbatch launch_sbatch_stance_mit.sh .65 .7
sbatch launch_sbatch_stance_mit.sh .7 .75
sbatch launch_sbatch_stance_mit.sh .75 .8
sbatch launch_sbatch_stance_mit.sh .8 .85
sbatch launch_sbatch_stance_mit.sh .85 .9
sbatch launch_sbatch_stance_mit.sh .9 .95
sbatch launch_sbatch_stance_mit.sh .95 1.00
